image: corndeldevopscourse/devops-course-starter-gitpod

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mhutchie.git-graph
    - ms-mssql.mssql
    - ms-python.python
    - eamodio.gitlens
    - hbenl.vscode-test-explorer
    - littlefoxteam.vscode-python-test-adapter